services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./docker/oracle-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle_data:
