services:
  oracle:
    image: gvenzl/oracle-xe:latest
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=weather-evaluator
      - APP_USER_PASSWORD=weather-evaluator
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle_data:
