ALTER SESSION SET CONTAINER = XEPDB1;

DECLARE
  v_exists INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM all_users WHERE username = 'WEATHER_EVALUATOR';
  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER WEATHER_EVALUATOR IDENTIFIED BY weather_evaluator';
  END IF;
END;
/